
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import {
    Swords, Target, Zap, Clock, Calendar,
    Trophy, Medal, Lock, CheckCircle2, Flame
} from "lucide-react";
import { cn } from "@/lib/utils";

const CHALLENGES = [
    {
        id: "streak_7",
        title: "Consistency King",
        description: "Deploy at least once every day for 7 days.",
        progress: 5,
        total: 7,
        xp: 500,
        reward: "🔥 7-Day Streak Badge",
        icon: Flame,
        color: "text-orange-500",
        bg: "bg-orange-500/10",
        status: "active"
    },
    {
        id: "speed_demon",
        title: "Speed Demon",
        description: "Achieve a build time under 45 seconds.",
        progress: 38,
        total: 45, // treating as current measurement to beat? Or maybe progress 1/1
        displayProgress: "38s / 45s",
        xp: 1000,
        reward: "⚡ Flash Badge",
        icon: Zap,
        color: "text-yellow-400",
        bg: "bg-yellow-400/10",
        status: "completed"
    },
    {
        id: "bug_hunter",
        title: "Bug Hunter",
        description: "Resolve 50 critical alerts generated by SentryBot.",
        progress: 12,
        total: 50,
        xp: 750,
        reward: "🛡️ Guardian Badge",
        icon: Target,
        color: "text-red-400",
        bg: "bg-red-400/10",
        status: "active"
    },
    {
        id: "night_owl",
        title: "Night Owl",
        description: "Deploy code between 2 AM and 5 AM local time.",
        progress: 0,
        total: 1,
        xp: 300,
        reward: "🦉 Owl Badge",
        icon: Clock,
        color: "text-indigo-400",
        bg: "bg-indigo-400/10",
        status: "locked"
    }
];

const BADGES = [
    { name: "Early Adopter", icon: "🚀", description: "Joined during beta." },
    { name: "First Deploy", icon: "📦", description: "Shipped your first project." },
    { name: "Speed Demon", icon: "⚡", description: "Build time < 45s." },
    { name: "Open Source", icon: "❤️", description: "Connected a public repo." },
];

export default function Challenges() {
    return (
        <div className="space-y-8">
            <div className="flex flex-col gap-2">
                <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
                    <Swords className="size-8 text-primary" />
                    Quests & Challenges
                </h1>
                <p className="text-muted-foreground">
                    Complete daily quests to earn XP, unlock badges, and level up your developer profile.
                </p>
            </div>

            {/* Level Progress */}
            <Card className="bg-gradient-to-r from-violet-600/20 to-indigo-600/20 border-violet-500/30">
                <CardContent className="p-6 flex flex-col md:flex-row items-center gap-6">
                    <div className="relative">
                        <div className="w-24 h-24 rounded-full border-4 border-violet-500 flex items-center justify-center bg-background text-3xl font-bold font-mono">
                            12
                        </div>
                        <div className="absolute -bottom-2 -right-2 bg-violet-600 text-white text-xs font-bold px-2 py-1 rounded-full border-2 border-background">
                            LEVEL
                        </div>
                    </div>
                    <div className="flex-1 w-full space-y-2">
                        <div className="flex justify-between text-sm font-medium">
                            <span>Experience Points</span>
                            <span className="text-violet-400">12,450 / 15,000 XP</span>
                        </div>
                        <Progress value={83} className="h-4 bg-background/50" indicatorClassName="bg-gradient-to-r from-violet-500 to-fuchsia-500" />
                        <p className="text-xs text-muted-foreground">
                            2,550 XP needed for Level 13 (Unlocks: Custom Themes)
                        </p>
                    </div>
                </CardContent>
            </Card>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {/* Active Challenges */}
                <div className="lg:col-span-2 space-y-4">
                    <h2 className="text-lg font-semibold flex items-center gap-2">
                        <Target className="size-5 text-primary" />
                        Active Quests
                    </h2>

                    <div className="grid gap-4">
                        {CHALLENGES.map((quest) => (
                            <Card key={quest.id} className={cn("transition-all", quest.status === 'locked' ? "opacity-60 grayscale bg-muted/30" : "")}>
                                <CardContent className="p-5">
                                    <div className="flex gap-4 items-start">
                                        <div className={cn("p-3 rounded-lg flex items-center justify-center shrink-0", quest.bg)}>
                                            <quest.icon className={cn("size-6", quest.color)} />
                                        </div>
                                        <div className="flex-1 space-y-3">
                                            <div className="flex justify-between items-start">
                                                <div>
                                                    <h3 className="font-bold text-base flex items-center gap-2">
                                                        {quest.title}
                                                        {quest.status === 'completed' && <CheckCircle2 className="size-4 text-emerald-500" />}
                                                        {quest.status === 'locked' && <Lock className="size-3 text-muted-foreground" />}
                                                    </h3>
                                                    <p className="text-sm text-muted-foreground mt-0.5">{quest.description}</p>
                                                </div>
                                                <Badge variant="secondary" className="font-mono text-xs">
                                                    +{quest.xp} XP
                                                </Badge>
                                            </div>

                                            {quest.status !== 'locked' && (
                                                <div className="space-y-1.5">
                                                    <div className="flex justify-between text-xs font-medium text-muted-foreground">
                                                        <span>Progress</span>
                                                        <span>{quest.displayProgress || `${quest.progress}/${quest.total}`}</span>
                                                    </div>
                                                    <Progress value={(quest.progress / quest.total) * 100} className="h-2" />
                                                </div>
                                            )}

                                            <div className="flex items-center gap-2 text-xs font-medium text-primary/80 pt-1">
                                                <Trophy className="size-3" />
                                                Reward: {quest.reward}
                                            </div>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                </div>

                {/* Badge Collection */}
                <div className="space-y-4">
                    <h2 className="text-lg font-semibold flex items-center gap-2">
                        <Medal className="size-5 text-amber-500" />
                        Trophy Case
                    </h2>
                    <Card>
                        <CardContent className="p-4 grid grid-cols-2 gap-4">
                            {BADGES.map((badge, i) => (
                                <div key={i} className="flex flex-col items-center justify-center text-center p-4 rounded-lg bg-muted/20 hover:bg-muted/40 transition-colors border border-border/50 group">
                                    <div className="text-4xl mb-2 group-hover:scale-110 transition-transform cursor-default select-none">
                                        {badge.icon}
                                    </div>
                                    <div className="font-semibold text-xs">{badge.name}</div>
                                    <div className="text-[10px] text-muted-foreground mt-1 line-clamp-1">{badge.description}</div>
                                </div>
                            ))}
                            {[1, 2, 3, 4].map((i) => (
                                <div key={`locked-${i}`} className="flex flex-col items-center justify-center text-center p-4 rounded-lg bg-muted/10 border border-dashed border-border/50 opacity-50">
                                    <Lock className="size-6 text-muted-foreground mb-2" />
                                    <div className="font-semibold text-xs text-muted-foreground">Locked</div>
                                </div>
                            ))}
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    );
}
